### ISSUE TITLE
Using @Inject constructor to inject fragments will result in NPEs after process death because they're created by the system and not Dagger

### ISSUE THREAD

**Issue by Zhuinden** [igorescodro/savel#12]

**Comment by igorescodro** [comment]
Hello, @Zhuinden 

Thanks for you feedback but this project is currently on hold since I'm working on [alkaa](https://github.com/igorescodro/alkaa).
I will resume _sävel_ soon and remake it in Kotlin and Koin so this issue will not be reproducible. :)
